#!/usr/bin/env bash
set -e
echo "Line 1: старт"
export APP_ENV="prod"
echo "Line 3: APP_ENV=$APP_ENV"
export VERSION="1.2.3"
echo "Line 5: VERSION=$VERSION"
echo "Line 6: проверка"
export PATH_EXTRA="/opt/tools"
echo "Line 8: PATH_EXTRA=$PATH_EXTRA"
echo "Line 9: сообщения"
echo "Line 10: всё ок"
export FLAG="true"
echo "Line 12: FLAG=$FLAG"
echo "Line 13: шаг"
echo "Line 14: шаг"
echo "Line 15: шаг"
export NAME="demo"
echo "Line 17: NAME=$NAME"
echo "Line 18: вывод"
echo "Line 19: вывод"
export REGION="ukwest"
echo "Line 21: REGION=$REGION"
echo "Line 22: финал"
echo "Line 23: финал"
export DATE="$(date +%F)"
echo "Line 25: DATE=$DATE"
echo "Line 26: done"
echo "Line 27: done"
echo "Line 28: done"
echo "Line 29: done"
echo "Line 30: done"
